// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qywicuiedcpwokojgoxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5d2ljdWllZGNwd29rb2pnb3hzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxODgwNjgsImV4cCI6MjA2ODc2NDA2OH0.ah0vSfQvekATmjsu74aj5LkflGJzndtUAE0FwMcyIAg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});